"""Cross-model comparison: which rules are load-bearing on model A but
dead on model B?

Verdict-level ONLY, by design. Each model has its own noise floor and
its own output-length/style distribution, so raw effect sizes are not
comparable across models — every verdict in the matrix was derived
against its own model's noise floor, and the report says so in a banner
rather than letting a reader treat effects as magnitudes.

Preconditions are the inverse of `check`: the prompt and corpus hashes
(and every verdict-affecting config field) must MATCH, while the models
must DIFFER. Both runs analyzed the same prompt, so segmentation is
identical and leaves pair by structural id.
"""

from __future__ import annotations

import json

from . import stats as st
from .check import PARITY_FIELDS, CheckError, _leaves

_UNKNOWN = {st.INHERITED, st.NOT_TESTED, None}

# model identity must differ; sampling/config identity must match
COMPARE_PARITY = tuple(f for f in PARITY_FIELDS if f != "model")


def compare_payloads(a: dict, b: dict) -> dict:
    ma, mb = a["meta"], b["meta"]
    if ma["prompt_sha256"] != mb["prompt_sha256"]:
        raise CheckError(
            f"prompt mismatch: run A analyzed prompt "
            f"{ma['prompt_sha256'][:12]}…, run B "
            f"{mb['prompt_sha256'][:12]}… — cross-model comparison needs "
            f"the identical prompt")
    if ma["corpus_sha256"] != mb["corpus_sha256"]:
        raise CheckError(
            f"corpus mismatch: run A used corpus "
            f"{ma['corpus_sha256'][:12]}…, run B "
            f"{mb['corpus_sha256'][:12]}…")
    for field in COMPARE_PARITY:
        if ma.get(field) != mb.get(field):
            raise CheckError(
                f"config mismatch on {field!r}: {ma.get(field)!r} vs "
                f"{mb.get(field)!r} — verdicts under different settings "
                f"reflect the settings, not the models")
    if ma["model"] == mb["model"]:
        raise CheckError(
            f"both reports were generated by {ma['model']!r} — compare "
            f"wants two different models (same-model diffing is "
            f"`promptcov check`)")

    leaves_a, leaves_b = _leaves(a), _leaves(b)
    if [x["id"] for x in leaves_a] != [x["id"] for x in leaves_b]:
        raise CheckError("segmentation differs despite identical prompt "
                         "hashes — reports were built by incompatible "
                         "promptcov versions")

    rows = []
    for la, lb in zip(leaves_a, leaves_b):
        va, vb = la.get("verdict"), lb.get("verdict")
        known = va not in _UNKNOWN and vb not in _UNKNOWN
        rows.append({"id": la["id"], "text": la["text"],
                     "a": va, "b": vb,
                     "unknown": not known,
                     "disagreement": known and va != vb})
    rows.sort(key=lambda r: (not r["disagreement"], r["unknown"], r["id"]))
    return {
        "model_a": ma["model"], "model_b": mb["model"],
        "metric": ma["metric"],
        "n_disagreements": sum(1 for r in rows if r["disagreement"]),
        "note": ("verdict-level comparison only: each verdict is relative "
                 "to its own model's noise floor; effect sizes are NOT "
                 "comparable across models"),
        "rows": rows,
    }


def render_compare(outcome: dict) -> str:
    data = json.dumps(outcome).replace("</", "<\\/")
    return _TEMPLATE.replace("__DATA__", data)


_TEMPLATE = r"""<!doctype html>
<html lang="en"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>promptcov · cross-model comparison</title>
<style>
:root{--chrome:#14181d;--line:#2a323d;--ink:#c9d3de;--dim:#7d8b99;
  --load:#c8502e;--ok:#3e8e5a;--warn:#c9a227}
*{box-sizing:border-box;margin:0}
body{background:var(--chrome);color:var(--ink);
  font-family:"IBM Plex Mono",ui-monospace,SFMono-Regular,Menlo,monospace;
  font-size:13px;line-height:1.55}
.wrap{max-width:1100px;margin:0 auto;padding:28px 22px 80px}
h1{font-family:"Space Grotesk",system-ui,sans-serif;color:#fff;
  font-size:clamp(22px,3vw,32px);margin-bottom:4px}
.banner{border:1px solid var(--warn);border-radius:4px;color:var(--warn);
  padding:8px 12px;margin:14px 0;font-size:12px}
table{border-collapse:collapse;width:100%;margin-top:14px}
th,td{border:1px solid var(--line);padding:6px 9px;text-align:left;
  vertical-align:top;font-size:12px}
th{color:var(--dim);text-transform:uppercase;letter-spacing:.08em;
  font-size:10.5px}
tr.dis td{background:#c8502e14}
td.v{white-space:nowrap}
.V-LOAD_BEARING{color:var(--load)}.V-NO_OBSERVED_EFFECT{color:var(--dim)}
.V-REDUNDANT{color:#7b5cd6}.V-UNEXERCISED{color:#1f8a8a}
.V-unknown{color:#4a5560}
.txt{white-space:pre-wrap;word-break:break-word}
</style></head><body><div class="wrap">
<h1>promptcov · cross-model comparison</h1>
<div id="sub" style="color:var(--dim)"></div>
<div class="banner" id="banner"></div>
<table><thead><tr><th>id</th><th>rule</th><th id="ha"></th>
<th id="hb"></th></tr></thead><tbody id="rows"></tbody></table>
</div><script>
const D = __DATA__;
document.getElementById("sub").textContent =
  `${D.model_a}  vs  ${D.model_b}  ·  metric ${D.metric}  ·  ` +
  `${D.n_disagreements} disagreement(s)`;
document.getElementById("banner").textContent = D.note;
document.getElementById("ha").textContent = D.model_a;
document.getElementById("hb").textContent = D.model_b;
const tb = document.getElementById("rows");
for (const r of D.rows) {
  const tr = document.createElement("tr");
  if (r.disagreement) tr.className = "dis";
  const v = x => x == null ? "unknown" : x;
  tr.innerHTML = `<td>${r.id}</td><td class="txt"></td>` +
    `<td class="v V-${v(r.a)}">${v(r.a)}</td>` +
    `<td class="v V-${v(r.b)}">${v(r.b)}</td>`;
  tr.children[1].textContent = r.text.trim();
  tb.appendChild(tr);
}
</script></body></html>
"""
